"""TaskStore protocol."""
from typing import Protocol
from ..core.models import Task


class TaskStore(Protocol):
    async def list_all(self) -> list[Task]: ...
    async def get(self, task_id: str) -> Task: ...
    async def read_instruction(self, task_id: str) -> str: ...
    async def read_aux_file(self, task_id: str, category: str, filename: str) -> str: ...
